### ISSUE TITLE
Consider converting the starter to a monorepo

### ISSUE THREAD

**Issue by asgorobets** [jakala-na/next-contentful-starterkit#70]
As a long-term goal for the starter, we strive to demonstrate real-world scenarios, in my experience building Contentful frontends rarely is limited to one frontend. Use-cases for monorepos include:
- Shared a UI library (already in a components/ui folder as it wants to be portable)
- Contentful Apps to support authoring experience needs, could live separately but if same teams develops more than one app and if some apps share business logic with frontend, for example search app, then why not have apps in the monorepo?
- CLI apps - things like generators or scaffolds, but also things like migrations CLIs wrappers for content model updates
- Queues/Crons/Migrations - running periodic migrations of data, using things like SQS for example can be beneficial for any Contentful app that relies on external data for import.
- Shared Contentful libs - in case of multiple Contentful spaces and frontends, monorepo can promote shared primitives to be developed as a library

We could start with pnpm/bun/yarn workspaces, but I'd rather go with Turborepo for better support of caching and dependency tracking.

*Inspirations:*
- [**Orbitkit**](https://github.com/ixahmedxi/orbitkit) - package-based Turborepo monorepo with opinionated Typescript build process for UI and libraries separate from apps, https://orbitkit.dev/decision-reasoning/why-all-built. The author was hired by NX team, which could mean he did something right =)
- [**Next Forge**](https://github.com/haydenbleasel/next-forge) - opinionated SaaS starter, similar to Orbitkit it is based on Typescript and Turborepo. At first glance it's a great starter, but it doesn't build packages with tsc, and potentially typescript inference time will depend on size of the codebase and will become slower (speculation)

**Comment by victorpavlov** [comment]
How about the https://nx.dev/? Or it's too much?

**Comment by asgorobets** [comment]
@victorpavlov I considered it, but opted for Turborepo for now. See https://github.com/jakala-na/next-contentful-starterkit/blob/main/docs/decisions/010-turborepo.md
